name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --index-url https://download.pytorch.org/whl/cpu torch torchvision --no-cache-dir
        pip install pytest matplotlib
    
    - name: Train model
      run: |
        python train.py
    
    - name: Run tests
      run: |
        pytest -v -s test_model.py
    
    - name: Upload trained model and augmentation samples
      uses: actions/upload-artifact@v4
      with:
        name: model-and-samples
        path: |
          mnist_model_*.pth
          augmentation_samples/*.png
        retention-days: 5